name: 3T Scripts to Octopus
on:
  workflow_dispatch:
env:
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_URL: "http://win2k12-srv4.icorp.local:8080"
  OCTOPUS_SPACE: 'Default'

jobs:
  scripts-3t:
    strategy:
      matrix:
        scriptfolders: [Test2,Test1]
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
           persist-credentials: false

      - name: Date Time Setup
        id: timedate
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
   #       format: "YYYY_MM_DD HH_mm_ss_SSS"
          format: "YYYY.MM.DD.ss"

      - name: Show Date Time
        run: |
          version=${{ steps.timedate.outputs.time }}.${GITHUB_RUN_NUMBER}
          echo "The time was ${{ steps.timedate.outputs.time }}.${GITHUB_RUN_NUMBER}"

  ##    - name: Get current date
  ##      id: set-version
  #      run: echo "::set-output name=date::$(date +"%Y-%m-%d")"
  ##      run: |
  ##        date_is=$date
  ##        echo "verson determined to be $date_is"
  ##        echo "verson determined to be $date_is" >> $GITHUB_OUTPUT

  #    - name: Set version
  #      id: set-version
  ##      run: |
   #        version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER
  #         echo "PACKAGE_VERSION determined to be $version"
  #         echo "PACKAGE_VERSION=$version" >> $GITHUB_OUTPUT

      - name: Create Zip package
        id: package
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
             package_id: ${{ matrix.scriptfolders }}
   #          version: ${{ steps.set-version.outputs.PACKAGE_VERSION }}
   #          version: ${{ steps.set-version.outputs.date_is }}
             version: "2.0.0"
             base_path: ${{ matrix.scriptfolders }}
             files: "**/*"
             output_folder: packaged

      - name: Push a package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        with:
         packages: ${{ steps.package.outputs.package_file_path }}
         overwrite_mode: OverwriteExisting
         
      - name: Push build information to Octopus Deploy 
        uses: OctopusDeploy/push-build-information-action@v3
        with:
   #        version: ${{ steps.set-version.outputs.PACKAGE_VERSION }}
   #        version: ${{ steps.set-version.outputs.date_is }}
           version: "2.0.0"
           packages: ${{ matrix.scriptfolders }}