on:
  workflow_call:
    secrets:
      TF_VAR_OCTOPUS_API_KEY:
        required: true

jobs:
  octopus:
    environment: ${{ inputs.environment }}
    runs-on: ${{ fromJSON(inputs.github_runner) }}
    env:
      TF_VAR_OCTOPUS_API_KEY: ${{secrets.TF_VAR_OCTOPUS_API_KEY}}
  
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.5

      - uses: actions/setup-node@v4
        with:
          node-version: 20

#      - name: Terraform plan
#        run: |
#          terraform init -reconfigure -no-color
#          terraform workspace select ${{ inputs.config_environment }} || terraform workspace new ${{ inputs.config_environment }}
#          terraform validate
#          terraform plan -input=false -lock=false -no-color -refresh=true -out=plan.out -var-file="environments/${{ inputs.config_environment }}/terraform.tfvars" -replace=octopusdeploy_deployment_process.stockbroking-release-orchestration
#          terraform show -json plan.out > plan.out.json

#      - name: Terraform apply
#        if: ${{ inputs.action == 'apply' }}
#        run: |
#          terraform apply -auto-approve -input=false -no-color plan.out
