name: 'Terraform-GitHub-Testing'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  nonprod-cd:
    uses: ./.github/workflows/_terraform.yml
    secrets:
      TF_VAR_OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          
