# This is a basic workflow to help you get started with Actions

name: terraformoctopus destroy

on: 
  workflow_dispatch:


jobs:
  terraform-destroy:
    name: Octopus Destroy
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_OCTOPUS_URL: ${{ vars.OCTOPUS_URL }}
      TF_VAR_OCTOPUS_ACCESS_TOKEN: ${{ steps.octopus_login.outputs.access_token }}
    defaults:
      run:
        working-directory: octopus

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Octopus using GitHub OIDC
        id: octopus_login
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ vars.OCTOPUS_URL }}
          service_account_id: ${{ vars.OCTOPUS_SERVICE_ACCOUNT_ID }}
         
#      - name: Terraform Init
#        run: |
#          terraform init -reconfigure -no-color

#      - name: Terraform Destroy
#        run: terraform destroy -auto-approve -no-color