# This is a basic workflow to help you get started with Actions

name: terraformoctopus

on: 
  push:
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  terraform:
     name: Octopus Build
     runs-on: self-hosted
     env:
      TF_VAR_OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
     defaults:
      run:
         working-directory: octopus

     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Plan
        run: |
          terraform init -reconfigure -no-color
          terraform validate
          terraform plan -input=false -no-color -refresh=true -out=plan.out 
          terraform show -json plan.out > plan.out.json
          