# This is a basic workflow to help you get started with Actions

name: terraformoctopus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  terraform:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
     runs-on: self-hosted
     name: Terraform Job
  #   uses: actions/checkout@v3
   
     steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.5

#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20

      - name: Terraform Plan
        run: |
          terraform init
##          terraform validate
##          terraform plan  -no-color
          
         
##      - name: Terraform Apply
##        run: |
##          terraform apply -auto-approve
         
      
 #     - name: Test Terraform Init
 #       id: init
 #       run: terraform init
 #       working-directory: C:\Software\octopus-terraform\octopus

 #     - name: Terraform Validate
 #       id: val
 #       run: terraform validate
 #       working-directory: C:\Software\octopus-terraform\octopus

 #     - id: plan
 #       run: terraform plan -no-color
 #       working-directory: C:\Software\octopus-terraform\octopus

 #     - id: apply
 #       run: terraform apply -auto-approve
 #       working-directory: C:\Software\octopus-terraform\octopus
      