# This is a basic workflow to help you get started with Actions

name: terraformoctopus

on: 
  push:
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  terraform:
     name: Octopus Build
     runs-on: self-hosted
     defaults:
      run:
         working-directory: octopus

     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Plan
        run: |
          terraform init