# This is a basic workflow to help you get started with Actions

name: terraformoctopus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  terraform-b:
    uses: ./.github/workflows/_terraform.yaml
    with:
      github-runner: "[\"self-hosted\"]"
    secrets:
      TF_VAR_OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY  }}
