# This is a basic workflow to help you get started with Actions

name: terraformoctopus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    paths:
      - "octopus/**"
      - "config/**/*.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  terraform:
     name: Octopus Build
     runs-on: self-hosted
     defaults:
      run:
         working-directory: octopus
         
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.5

      - name: Terraform Plan
        run: |
          terraform init